# core setup features
year: 2025
event_code: "njdd"
run_with_tba: false
path_to_data: "data/2025njdd_match_data.json"
path_to_output: "data/errors.json"

# required translation
scout_id: "ScoutId"
match_key: "MatchKey"
team_number: "TeamNumber"
alliance: "Alliance"
driver_station": "DriverStation"

# optional parameters - if it is needed for a data check and is
# not listed, the check will not run

# Reefscape 2025: hyper-specific parameters
auto_starting_position: "StartingPosition"
auto_scoring_side: "ScoringSide"
auto_singular_count: "AutoSingularCount"
auto_batch_count: "AutoBatchCount"
teleop_singular_count: "TeleopSingularCount"
teleop_batch_count: "TeleopBatchCount"
auto_climb_status: "AutoClimb"
teleop_climb_status: "TeleopClimb"
teleop_climb_speed: "ClimbSpeed"
disabled: "Disabled"
stability_rating: "StabilityRating"
robot_style_type: "RobotStyleType"
driver_rating: "DriverRating"
intake_defense_rating: "IntakeDefenseRating"

# parameters for notes
auto_notes: "AutoNotes"
teleop_notes: "TeleopNotes"
endgame_notes: "EndgameNotes"
rating_notes: "RatingNotes"
